name: Build and deploy container app to Azure Web App - middlewaredocmanagement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://crdockercontainer.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_ebb5c95e3ebe40e4813107811e0ecdbb }}
          password: ${{ secrets.AzureAppService_ContainerPassword_4e6652e43e654304927ddb58a378ebd1 }}

      - name: Build and push container image with HF token
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
          tags: crdockercontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ebb5c95e3ebe40e4813107811e0ecdbb }}/fastapi-libreoffice:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'middlewaredocmanagement'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a0fa3ecba9bf45e286f917e678c568a8 }}
          images: 'crdockercontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ebb5c95e3ebe40e4813107811e0ecdbb }}/fastapi-libreoffice:${{ github.sha }}'